### ISSUE TITLE
Does this work with the Laser 128?

### ISSUE THREAD

**Issue by cbmeeks** [rowokii/A2C_TangyPack#2]
I have both versions of the Laser 128.  Do you know if they would work with them?

Also, on a different note, are you the same guy that designed the internal Mockingboard clone for the IIc?

Thanks!

**Comment by rowokii** [comment]
Right now, it does not work with the Laser 128.   I might be able to get it to work with a Laser 128 for monochrome mode if I remap the CSYNC signal, but it is missing the CREF signal I need to generate color images.   I will explore this a bit more once I ship out the current batch of devices.

**Comment by cbmeeks** [comment]
Ah, sorry.  I bought the Mockingboard clone from him many years ago and couldn't remember his name.

Thanks.

**Comment by rowokii** [comment]
Hi,  Just FYI... Laser 128 support has been added with Firmware V1.10.  
https://github.com/rowokii/A2C_TangyPack/blob/main/Laser128.md
