### ISSUE TITLE
HDMI does not work, VGA is shifted too much to use

### ISSUE THREAD

**Issue by dillera** [rowokii/A2C_TangyPack#5]
Just got one and HDMI doesn't work on any monitor I have, used the VGA w/ a VGA to HDMI upscaler and that works but image is shifted to the left too much to be useable.

Any chance there will be controls to shift the image placement?

Video:
https://www.facebook.com/100001338738932/videos/2092824124447787/

**Comment by rowokii** [comment]
Hi Andrew,

Sorry to hear about your problems with the HDMI output.   The video output is not standard resolution and some monitors and especially capture cards seems to be very particular about the signaling.  This is definitely something I want to try to improve, but I have not had much time work on it yet.  

Regarding centering the image.  Can you try to turn on the border right away after you turn on the device.  Or, can you re-trigger your capture card's auto sync?  The image from the Tangy Pack is centered, but the image does not take up the full screen.  By the time you turn on the border, your device has already decided on how big the image is and shifting it.

**Comment by dillera** [comment]
I've looked for an auto-sync but I don't think there is one. I've tried to turn on the boarder as soon as the IIC powers on but that does not seem to make much of a difference.

**Comment by rowokii** [comment]
Well, if you are willing to try updating the firmware, I can upload a new firmware that default starts with the border turned on.

Also, regarding the slowness of the device, it's something else in the video signal chain that is introducing the lag.  Tangy Pack is scan doubling the image coming from the Apple IIc, which means it has something in the order of <200uS of delay between the composite video output and VGA output.  You should not be able to see that difference.

**Comment by rowokii** [comment]
Under the firmware folder: 

 A2C_TangyPack_V1p00_wb.fs 

This is the firmware that has the white border turned on my default

**Comment by rowokii** [comment]
I had another idea about why the image could be shifting.  I removed the above firmware image and put two new firmware in the Experimental folder.  If so inclined, can you try to flash the firmware with _WB.fs ending to see if this fixes your image shifting problem?

**Comment by dillera** [comment]
Absolutely, thanks for thinking about this and spending some time on it. I'll try and update this thread today.

**Comment by dillera** [comment]
Success!
$ openFPGAloader -b tangnano9k -f ~/Downloads/A2C_TangyPack_V1p00_sync_invert_exp_WB.fs
Using that does center it now at least VGA->VGA/HDMI Upscaler.

<img width="1283" alt="Screenshot 2024-10-18 at 9 56 10 AM" src="https://github.com/user-attachments/assets/89a57bc9-9850-4335-b37b-b7f50c9f4086">

**Comment by dillera** [comment]
There is that one white vertical strip all the way on the right of the image that is not part of the boarder and does not go away. Other than that it seems to work nicely and I can remove the border via the button, using FujiNet to boot an image and the Tangy does not reset (it stays centered).
<img width="648" alt="Screenshot 2024-10-18 at 10 19 26 AM" src="https://github.com/user-attachments/assets/ea688f49-5cb3-4c20-8c70-a58fee44f726">

**Comment by rowokii** [comment]
OK, progress...  

Hum... I know I overscaned the image horizontally a bit because Apple II annoyingly shift the image horizontally depending on display mode.  I thought the amount I overscanned was benign since  most of the software I tested had black in the overscan area, but I guess not.

I think you mentioned this is FujiNet.   I don't have FujiNet so I'm very ignorant of how it works, but is it possible to run the software without having the FujiNet device?  I just need the software to run enough to have a display output.

**Comment by dillera** [comment]
Oh yes, FujiNet just loads disk images, you don't need FujiNet and it in no way interferes with this- it's just the way i can load an application.

Speaking of that where are the image demo utils you run in your video? The ones that show the color bars etc?

Where as in where can I download them and run them on my iic?

**Comment by rowokii** [comment]
OK.  Two new firmwares in the Experimental folder.   The ones with hov_exp.fs and hov_exp_WB.fs endings.  These removes the horizontal overscans areas from displaying.   _WB.fs is the one that has the default white border like last time.

Regarding the image demos...  it's just some basic software I wrote to exercise various display modes and colors.    Uploaded under /Software folder.  It's a DOS 3.3 dsk image.

**Comment by dillera** [comment]
Ok, the overscan lines are gone! I will test this further- and thanks again for sorting this out.
<img width="725" alt="Screenshot 2024-10-19 at 11 59 27 AM" src="https://github.com/user-attachments/assets/59431372-7830-4918-a453-2a06d20e05df">

**Comment by dillera** [comment]
This works nicely- hopefully you can get HDMI going on some capture devices!
